import ReduxShell from 'components/shells/reduxShell';

import { CssBaseline } from '@material-ui/core';
import 'styles/globals.scss';
import './index.scss';
import '@fontsource/roboto';

import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Table tennis overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReduxShell>
        <CssBaseline />
        <Component {...pageProps} />
      </ReduxShell>
    </>
  );
}

export default MyApp;
