import { Container } from "@material-ui/core";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Table tennis overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="lg">
        <h1>Статистика по настольному теннису</h1>
      </Container>
    </div>
  );
}
